version: "3"

services:
  database:
    image: postgres:11
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
